CREATE TABLE Products (
    Id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);

CREATE TABLE Sales (
    Id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SaleDate TIMESTAMP NOT NULL,
    Customer VARCHAR(255) NOT NULL,
    Store VARCHAR(255),
    IsCanceled BOOLEAN DEFAULT FALSE
);

CREATE TABLE SaleItems (
    Id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SaleId INT NOT NULL,
    ProductId INT NOT NULL,
    ProductDescription VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    UnitPrice DECIMAL(10,2) NOT NULL CHECK (UnitPrice > 0),
    Discount DECIMAL(10,2) DEFAULT 0 CHECK (Discount >= 0),
    TotalPrice DECIMAL(10,2) CHECK (TotalPrice >= 0),

    CONSTRAINT fk_sale FOREIGN KEY (SaleId) REFERENCES Sales(Id) ON DELETE CASCADE,
    CONSTRAINT fk_product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE CASCADE
);
